### ISSUE TITLE
[UI/UX] Copying command on individual package's page should only copy the displayed command

### ISSUE THREAD

**Issue by Weilbyte** [winget-run/web#38] opened 2020-07-16 09:31 UTC
As the title suggests, copying the install command of an individual package should only copy the displayed install command, without prepending `powershell` and appending `exit`. 

As an example, if we take look at the displayed install command for Origin, its `winget install -e --id ElectronicArts.Origin` but upon clicking the Copy button to the right of the block, what ends up in our clipboard is instead:
```
powershell
winget install -e --id ElectronicArts.Origin

exit
```

Which is clearly not what we intended to copy.

**Comment by MattheousDT** [comment] 2020-07-16 20:09
Hey, closing this as it's a duplicate of #21 . This has been fixed on our develop branch and should be pushed to production this weekend.

**Closed by MattheousDT** 2020-07-16 20:09 UTC
Labels: duplicate

**Comment by Weilbyte** [comment] 2020-07-16 20:19
Ah didn't realize that was about this. Cheers!

**Comment by MattheousDT** [comment] 2020-07-19 20:14
@Weilbyte This has been deployed now.
